# Generated by Django 4.2 on 2023-05-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0005_subscribedusers_delete_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribedUsers',
        ),
    ]
