# Generated by Django 4.2 on 2023-05-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0007_alter_customer_email_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
