# Generated by Django 4.2 on 2023-05-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0009_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
